/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTimelineRouteImport } from './routes/dashboard.timeline'
import { Route as DashboardSimulatorRouteImport } from './routes/dashboard.simulator'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSemestersIndexRouteImport } from './routes/dashboard.semesters.index'
import { Route as DashboardSemestersIdRouteImport } from './routes/dashboard.semesters.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTimelineRoute = DashboardTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSimulatorRoute = DashboardSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSemestersIndexRoute = DashboardSemestersIndexRouteImport.update({
  id: '/semesters/',
  path: '/semesters/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSemestersIdRoute = DashboardSemestersIdRouteImport.update({
  id: '/semesters/$id',
  path: '/semesters/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulator': typeof DashboardSimulatorRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/semesters/$id': typeof DashboardSemestersIdRoute
  '/dashboard/semesters/': typeof DashboardSemestersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulator': typeof DashboardSimulatorRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/semesters/$id': typeof DashboardSemestersIdRoute
  '/dashboard/semesters': typeof DashboardSemestersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/simulator': typeof DashboardSimulatorRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/semesters/$id': typeof DashboardSemestersIdRoute
  '/dashboard/semesters/': typeof DashboardSemestersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/settings'
    | '/dashboard/simulator'
    | '/dashboard/timeline'
    | '/dashboard/'
    | '/dashboard/semesters/$id'
    | '/dashboard/semesters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/settings'
    | '/dashboard/simulator'
    | '/dashboard/timeline'
    | '/dashboard'
    | '/dashboard/semesters/$id'
    | '/dashboard/semesters'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/settings'
    | '/dashboard/simulator'
    | '/dashboard/timeline'
    | '/dashboard/'
    | '/dashboard/semesters/$id'
    | '/dashboard/semesters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/timeline': {
      id: '/dashboard/timeline'
      path: '/timeline'
      fullPath: '/dashboard/timeline'
      preLoaderRoute: typeof DashboardTimelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/simulator': {
      id: '/dashboard/simulator'
      path: '/simulator'
      fullPath: '/dashboard/simulator'
      preLoaderRoute: typeof DashboardSimulatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/semesters/': {
      id: '/dashboard/semesters/'
      path: '/semesters'
      fullPath: '/dashboard/semesters/'
      preLoaderRoute: typeof DashboardSemestersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/semesters/$id': {
      id: '/dashboard/semesters/$id'
      path: '/semesters/$id'
      fullPath: '/dashboard/semesters/$id'
      preLoaderRoute: typeof DashboardSemestersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSimulatorRoute: typeof DashboardSimulatorRoute
  DashboardTimelineRoute: typeof DashboardTimelineRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSemestersIdRoute: typeof DashboardSemestersIdRoute
  DashboardSemestersIndexRoute: typeof DashboardSemestersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSimulatorRoute: DashboardSimulatorRoute,
  DashboardTimelineRoute: DashboardTimelineRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSemestersIdRoute: DashboardSemestersIdRoute,
  DashboardSemestersIndexRoute: DashboardSemestersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
